#=================================================
# Description: Build V2X2 using GitHub Actions
# Lisence: MPL-2.0
# Peace and joy
#=================================================

name: Actions-V2X2

on:
  workflow_dispatch:
  #schedule:
  # - cron: 0 16 * * *

env:
  SOURCE_URL: https://github.com/XTLS/Xray-core
  SOURCE_BRANCH: main
  DIY_SH: custom.sh
  UPLOAD_RELEASE: true
  GO_VER: 1.20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Initialization environment
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $SOURCE_URL -b $SOURCE_BRANCH v2x2
        ln -sf /workdir/v2x2 $GITHUB_WORKSPACE/v2x2

    - name: Replace Custom to Commit ID
      run: |
        cd $GITHUB_WORKSPACE/v2x2/
        sed -i '/build/ s/Custom/''/' $GITHUB_WORKSPACE/v2x2/core/core.go
        sed -i '/codename/ s/Xray, Penetrates Everything./''/' $GITHUB_WORKSPACE/v2x2/core/core.go
        sed -i '/intro/ s/A unified platform for anti-censorship./''/' $GITHUB_WORKSPACE/v2x2/core/core.go
        sed -i '/serial.Concat/ s/Xray/'Server.js'/' $GITHUB_WORKSPACE/v2x2/core/core.go

    - name: Setup GO
      uses: actions/setup-go@main
      with:
        go-version: '${{ env.GO_VER }}'
        check-latest: true

    - name: Get project dependencies
      run: |
        go get -v -t -d $GITHUB_WORKSPACE/v2x2/go.mod
        go mod download

    - name: Build v2x2-binary
      run: |
        cd $GITHUB_WORKSPACE/v2x2/
        go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main

    - name: Check space usage
      if: (!cancelled())
      run: df -hT 
