#=================================================
# Description: Build V2X2 using GitHub Actions
# Lisence: MPL-2.0
# Peace and joy
#=================================================

name: Actions-V2X2

on:
  workflow_dispatch:
  #schedule:
  # - cron: 0 16 * * *

env:
  SOURCE_URL: https://github.com/XTLS/Xray-core.git
  UPLOAD_RELEASE: true
  GO_VER: 1.20

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Initialization environment
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $SOURCE_URL v2x2
        ln -sf /workdir/v2x2 $GITHUB_WORKSPACE/v2x2

    - name: Replace Custom to Commit ID
      run: |
        cd $GITHUB_WORKSPACE/v2x2/
        sed -i '/build/ s/Custom/''/' $GITHUB_WORKSPACE/v2x2/core/core.go
        sed -i '/codename/ s/Xray, Penetrates Everything./''/' $GITHUB_WORKSPACE/v2x2/core/core.go
        sed -i '/intro/ s/A unified platform for anti-censorship./''/' $GITHUB_WORKSPACE/v2x2/core/core.go
        sed -i '/serial.Concat/ s/Xray/'server.js'/' $GITHUB_WORKSPACE/v2x2/core/core.go

    - name: Build v2x2-binary
      run: |
        cd $GITHUB_WORKSPACE/v2x2/ && go mod download
        go build -o server.js -trimpath -ldflags "-s -w -buildid=" ./main
        ls -alF $GITHUB_WORKSPACE/v2x2/* | grep server.js

    - name: Check space usage
      if: (!cancelled())
      run: df -hT 
