#=================================================
# Description: Build V2X2 using GitHub Actions
# Lisence: MPL-2.0
# Peace and joy
#=================================================

name: Actions-V2X2

on:
  workflow_dispatch:
  #schedule:
  # - cron: 0 16 * * *

env:
  SOURCE_URL: https://github.com/XTLS/Xray-core
  SOURCE_BRANCH: main
  DIY_SH: custom.sh
  UPLOAD_RELEASE: true
  GO_VER: 1.20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install curl wget tar zip unzip gcc git make
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $SOURCE_URL -b $SOURCE_BRANCH v2x2
        ln -sf /workdir/v2x2 $GITHUB_WORKSPACE/v2x2

    - name: Load custom files
      run: |
        [ -e $DIY_SH ] && mv $DIY_SH $GITHUB_WORKSPACE/v2x2/core/core.go
    
    - name: Setup GO
      uses: actions/setup-go@main
      with:
        go-version: '${{ env.GO_VER }}'
        check-latest: true

    - name: Get project dependencies
      run: |
        cd $GITHUB_WORKSPACE/v2x2
        go mod download
    
    - name: Build v2x2-binary
      run: |
        go build -o server.js -trimpath -ldflags "-s -w -buildid=" ./main

    - name: Check space usage
      if: (!cancelled())
      run: df -hT 
